MVC_Product_Shop/Models/Product.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace MVC_Product_Shop.Models
{
    public class Product
    {
        [BindNever]
        public int ProductId { get; set; }
        [BindRequired]
        public string Name { get; set; } = "";
        public string? Description { get; set; }
        [BindRequired]
        public decimal Price { get; set; }
        public bool IsFeaturedProduct { get; set; }
        [BindRequired]
        public int CategoryId { get; set; }
        [BindNever]
        public Category Category { get; set; } = default!;
    }
}

MVC_Product_Shop/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Product_Shop.Models;
using MVC_Product_Shop.ViewModels;
using System.Diagnostics;

namespace MVC_Product_Shop.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;
        private Stopwatch _stopwatch;

        public ProductController(IProductRepository productRepository, ICategoryRepository categoryRepository)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
            _stopwatch = new Stopwatch();
        }

        public IActionResult List(string category)
        {
            _stopwatch.Restart();
            IEnumerable<Product> products;
            string? currentCategory;

            if (string.IsNullOrEmpty(category))
            {
                products = _productRepository.AllProducts.OrderBy(p => p.ProductId);
                currentCategory = "All products";
            }
            else
            {
                currentCategory = _categoryRepository.AllCategories.FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
                products = _productRepository.GetProductsForCategory(currentCategory);
            }

            _stopwatch.Stop();
            return View(new ProductListViewModel(products, _categoryRepository.AllCategories, currentCategory));
        }

        public IActionResult Details(int id)
        {
            _stopwatch.Restart();
            var product = _productRepository.GetProductById(id);
            if (product == null)
            {
                return NotFound();
            }

            _stopwatch.Stop();
            return View(product);
        }

        public IActionResult FilteredList(string searchString)
        {
            _stopwatch.Restart();
            IEnumerable<Product> products;
            string currentCategory = "All products";

            if (string.IsNullOrEmpty(searchString))
            {
                products = _productRepository.AllProducts.OrderBy(p => p.ProductId);
            }
            else
            {
                products = _productRepository.SearchProducts(searchString);
            }
            _stopwatch.Stop();
            return View("List", new ProductListViewModel(products, _categoryRepository.AllCategories, currentCategory));
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View(new ProductAddViewModel(_categoryRepository.AllCategories));
        }

        [HttpPost]
        public IActionResult Add(Product product) 
        {
            _stopwatch.Restart();
            //if(!ModelState.IsValid)
            //{
            //    return BadRequest(product);
            //}

            product.Category = _categoryRepository.AllCategories.First(c => c.CategoryId == product.CategoryId);
            _productRepository.AddProduct(product);

            _stopwatch.Stop();
            return RedirectToAction("List");            
        }
    }
}

MVC_Product_Shop/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Product_Shop.Models;
using MVC_Product_Shop.ViewModels;
using System.Diagnostics;

namespace MVC_Product_Shop.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly IShoppingCart _shoppingCart;
        private Stopwatch _stopwatch;

        public ShoppingCartController(IProductRepository productRepository, IShoppingCart shoppingCart)
        {
            _productRepository = productRepository;
            _shoppingCart = shoppingCart;
            _stopwatch = new Stopwatch(); 
        }

        public IActionResult Index()
        {
            _stopwatch.Restart();

            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel(_shoppingCart, _shoppingCart.GetShoppingCartTotal());

            _stopwatch.Stop();
            return View(shoppingCartViewModel);
        }

        public RedirectToActionResult AddToShoppingCart(int productId)
        {
            _stopwatch.Restart();
            var selectedProduct = _productRepository.AllProducts.FirstOrDefault(p => p.ProductId == productId);

            if (selectedProduct != null)
            {
                _shoppingCart.AddToCart(selectedProduct);
            }

            _stopwatch.Stop();
            return RedirectToAction("Index");            
        }

        public RedirectToActionResult RemoveFromShoppingCart(int productId)
        {
            var selectedProduct = _productRepository.AllProducts.FirstOrDefault(p => p.ProductId == productId);

            if (selectedProduct != null)
            {
                _shoppingCart.RemoveFromCart(selectedProduct);
            }
            return RedirectToAction("Index");
        }
    }
}

MVC_Product_Shop/Views/Product/Add.cshtml
@model ProductAddViewModel

<h1>Product Page</h1>
<div>
    @using (Html.BeginForm("Add", "Product", FormMethod.Post)){
        <div class="form-group">
            <label asp-for="Product.Name" class="form-label">Product: </label>
            @Html.TextBoxFor(m => m.Product.Name, new {@class = "form-control"})
        </div>
        <div class="form-group">
            <label asp-for="Product.Price" class="form-label">Price: </label>
            @Html.TextBoxFor(m => m.Product.Price, new { @type = "number", step="any" })
        </div>
        <div>
            <label asp-for="Product.Description" class="form-label"></label>
            <textarea class="form-control" rows="3"></textarea>
        </div>
        <div class="form-group">
            <label asp-for="Product.Category" class="form-label"></label>
            @Html.DropDownListFor(m => m.Product.CategoryId, new SelectList(Model.Categories, "CategoryId", "CategoryName"), new {@class = "form-select"})
        </div>
        <div class="form-check">
            <label asp-for="Product.IsFeaturedProduct" class="form-check-label"></label>
            @Html.CheckBoxFor(m => m.Product.IsFeaturedProduct, new {@class = "form-check-input"})
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Add new Product</button>
        </div>
    }
</div>

MVC_Product_Shop/Views/Product/Details.cshtml
@model Product

<h3 class="my-5">
	@Model.Name
</h3>

<div class="row gx-5">
	<div class="col-7">
		<p>@Model.Description</p>
		<h3 class="pull-righ">@Model.Price.ToString("c")</h3>
		<div class="addToCart">
			<p class="button">
				<a class="btn btn-secondary"
				   asp-controller="ShoppingCart"
				   asp-action="AddToShoppingCart"
				   asp-route-productId="@Model.ProductId">Add to cart</a>
			</p>
		</div>
	</div>
</div>

MVC_Product_Shop/Views/Product/List.cshtml
@model ProductListViewModel
<h1>Product Page</h1>
<div>
    @using (Html.BeginForm("FilteredList", "Product", FormMethod.Post)){
        @Html.TextBoxFor(m => m.SearchString)
        <button type="submit" class="btn btn-primary">Search</button>
    }
</div>

<h1>@Model.CurrentCategory</h1>

<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Dropdown button
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        @{
            <li>
                <a asp-controller="Product"
                   asp-action="List"
                   asp-route-category=""
                   class="product-link">All categories</a>
            </li>
            foreach(var category in Model.Categories)
            {
                <li>
                    <a asp-controller="Product"
                       asp-action="List"
                       asp-route-category="@category.CategoryName"
                       class="product-link">@category.CategoryName</a>
                </li>
            }

        }
    </ul>
</div>

<div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Price</th>
                <th scope="col">Featured</th>
                <th scope="col">Category</th>
                <th scope="col">Buy Product</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var product in Model.Products){
                <tr>
                    <th scope="row">
                        <a asp-controller="Product"
                            asp-action="Details"
                            asp-route-id="@product.ProductId"
                            class="product-link">@product.Name
                        </a>
                    </th>
                    <td>@product.Price.ToString("c")</td>
                    <td>
                        @(product.IsFeaturedProduct ?  "Yes" : "No" )
                    </td>
                    <td>@product.Category.CategoryName</td>
                    <td>
                        <a class="btn btn-secondary"
                           asp-controller="ShoppingCart"
                           asp-action="AddToShoppingCart"
                           asp-route-productId="@product.ProductId">+ Add to cart</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>